# Generated by Django 2.0.6 on 2018-06-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('body', models.TextField(verbose_name='Conteúdo HTML')),
                ('js_code', models.TextField(blank=True, default='', verbose_name='Código Javascript')),
                ('custom_css', models.TextField(blank=True, default='', verbose_name='CSS Customizado')),
                ('extra_head', models.TextField(blank=True, default='', verbose_name='Extra head')),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
            },
        ),
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Texto da pergunta')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
            },
        ),
        migrations.AddField(
            model_name='action',
            name='questions',
            field=models.ManyToManyField(related_name='actions', to='actions.QuestionTag', verbose_name='Conteúdo HTML'),
        ),
    ]
