# Generated by Django 2.0.6 on 2018-06-15 23:02

from django.db import migrations


def populate_questions_tags(apps, schema_editor):
    QuestionTag = apps.get_model('actions.QuestionTag')

    question_texts = [
        "O que hoje é presença?",
        "O que os não especialistas têm a dizer?",
        "O que reverbera?",
        "O que fica?",
    ]

    for q in question_texts:
        QuestionTag.objects.create(title=q)


def rollback(apps, schema_editor):
    QuestionTag = apps.get_model('actions.QuestionTag')
    QuestionTag.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            populate_questions_tags,
            rollback
        )
    ]
