# Generated by Django 2.0.6 on 2018-07-03 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_auto_20180703_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
