# Generated by Django 2.0.6 on 2018-07-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_action_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='action_date',
            field=models.DateField(null=True, verbose_name='Data da ação'),
        ),
    ]
