# Generated by Django 2.0.6 on 2018-07-09 19:48

from django.db import migrations


def populate_action_date(apps, schema_editor):
    Action = apps.get_model('actions.Action')
    for action in Action.objects.all():
        action.action_date = action.date_added.date()
        action.save()


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_action_action_date'),
    ]

    operations = [
        migrations.RunPython(populate_action_date)
    ]
