# Generated by Django 2.0.6 on 2018-07-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_auto_20180709_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='date_added',
        ),
        migrations.AlterField(
            model_name='action',
            name='action_date',
            field=models.DateField(verbose_name='Data da ação'),
        ),
    ]
