# Generated by Django 2.0.6 on 2018-07-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0007_auto_20180709_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Publicar?'),
        ),
    ]
