# Generated by Django 2.0.6 on 2018-07-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0008_action_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Publicada'),
        ),
    ]
