# Generated by Django 2.0.6 on 2018-07-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0009_auto_20180718_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('upload', models.FileField(blank=True, null=True, upload_to='contacts/')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
    ]
