# Generated by Django 2.0.6 on 2018-07-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0010_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='contacts/', verbose_name='Envio de Arquivo'),
        ),
    ]
