# Generated by Django 2.0.6 on 2018-07-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0011_auto_20180720_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_date',
            field=models.DateField(auto_now_add=True, verbose_name='Data da ação'),
        ),
    ]
