# Generated by Django 2.0.6 on 2018-07-21 17:17

from django.db import migrations, models
import yamlfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0011_auto_20180720_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', yamlfield.fields.YAMLField(default=dict)),
                ('action', models.ForeignKey(on_delete='CASCADE', related_name='carousel', to='actions.Action')),
            ],
        ),
    ]
