# Generated by Django 2.0.6 on 2018-07-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0014_analyzedimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedimage',
            name='upload',
            field=models.ImageField(default='', upload_to='carousel/', verbose_name='Imagem'),
            preserve_default=False,
        ),
    ]
