# Generated by Django 2.0.6 on 2018-07-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0015_analyzedimage_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyzedimage',
            old_name='upload',
            new_name='image',
        ),
    ]
