# Generated by Django 2.0.6 on 2018-07-21 17:41

from django.db import migrations, models
import yamlfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0016_auto_20180721_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyzedimage',
            options={'ordering': ['order'], 'verbose_name': 'Imagem Analisada', 'verbose_name_plural': 'Imagens Analisadas'},
        ),
        migrations.AlterField(
            model_name='analyzedimage',
            name='info',
            field=yamlfield.fields.YAMLField(default=''),
        ),
        migrations.AlterField(
            model_name='analyzedimage',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Posição'),
        ),
    ]
