# Generated by Django 2.0.6 on 2018-07-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0019_auto_20180721_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedimage',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Data'),
        ),
    ]
