# Generated by Django 2.0.6 on 2018-08-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0020_auto_20180723_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['title'], 'verbose_name': 'Ação', 'verbose_name_plural': 'Ações'},
        ),
        migrations.AddField(
            model_name='questiontag',
            name='description',
            field=models.TextField(default='', verbose_name='Descrição'),
        ),
    ]
