# Generated by Django 2.0.6 on 2018-08-08 17:39

from django.db import migrations


def populate_tags_description(apps, schema_editor):
    QuestionTag = apps.get_model('actions.QuestionTag')
    data = {
        'O que hoje é presença?': "Experiências que expandem a ideia de visitar a 33ª Bienal de São Paulo. Quais são as mudanças de compreensões quando se recusa a se estar presencialmente na exposição, evitando o discurso oficial ali construído e a fisicalidade dos objetos ali expostos? Como o registro publicado na internet expande a relação de fisicalidade entre o corpo do visitante e o espaço expositivo?",
        'O que os não especialistas têm a dizer?': "Experiências que buscam mostrar que o discurso oficial da curadoria, dos artistas participantes e da instituição construídos e propagados na 33ª Bienal é apenas um conjunto de muitos outros modos discursivos. Para além da oficialidade discursiva, há uma série de outras compreensões possíveis como as dos guardas e do pessoal de limpeza do prédio que diariamente convivem com a arte ali construída. Resultados não esperados também são produzidos quando imagens da 33ª Bienal são lidas por ferramentas digitais não totalmente treinadas para entender registros de exposições e de obras de arte.",
        'O que reverbera?': "De que maneira o prédio da Bienal, os trajetos possíveis da exposição e as leituras publicadas nos veículos de comunicação afetam nosso corpo, nossa memória e nossa compreensão? Estamos aqui interessados em rotas possíveis no espaço, reverberações inesperadas da exposição no parque, na cidade de São Paulo e no mundo, assim como utilizar a 33ª Bienal como ponto inicial de estímulo para emigrantes brasileiros compartilharem e reconstruirem seus afetos com o Brasil.",
        'O que fica?': "Até dezembro de 2018, uma série de esforços será feito pela instituição para produzir registros que irão determinar o arquivo oficial da 33ª Bienal. Muitas dessas operações também foram recorrentes em edições passadas, criando uma espécie de modo comum controlar a compreensão do passado. As ações aqui buscam revelar como esses modos de controle são construídos, assim como discutir como esse projeto pode se tornar uma fresta inesperada no arquivo da instituição.",
    }

    for title, description in data.items():
        QuestionTag.objects.filter(title=title).update(description=description)


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0021_auto_20180808_1438'),
    ]

    operations = [
        migrations.RunPython(populate_tags_description)
    ]
