# Generated by Django 2.0.6 on 2018-08-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0022_auto_20180808_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedimage',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
