# Generated by Django 2.0.6 on 2018-08-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0023_auto_20180827_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='action_date',
        ),
    ]
