# Generated by Django 2.0.6 on 2018-08-28 20:46

from django.db import migrations, models
import tinymce.models
import yamlfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0025_auto_20180828_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='body_en',
            field=tinymce.models.HTMLField(default='', verbose_name='Conteúdo (EN)'),
        ),
        migrations.AddField(
            model_name='action',
            name='title_en',
            field=models.CharField(default='', max_length=100, verbose_name='Título (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analyzedimage',
            name='info_en',
            field=yamlfield.fields.YAMLField(default='', verbose_name='Resultados da Análise (EN)'),
        ),
        migrations.AddField(
            model_name='analyzedimage',
            name='title_en',
            field=models.CharField(default='', max_length=100, verbose_name='Nome (EN)'),
        ),
        migrations.AlterField(
            model_name='action',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='questiontag',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Pergunta'),
        ),
    ]
