# Generated by Django 2.0.6 on 2018-08-28 20:55
import yaml
from django.db import migrations


default = {
    'analise': [],
    'produtos': [],
    'categoria': '',
    'thumbnails': []
}
default_yaml = yaml.dump(default)


def copy_analyses_texts(apps, schema_editor):
    AnalyzedImage = apps.get_model('actions.AnalyzedImage')

    for img in AnalyzedImage.objects.all():
        img.info, img.info_en = default_yaml, img.info
        img.save()


def copy_back_analyses_texts(apps, schema_editor):
    AnalyzedImage = apps.get_model('actions.AnalyzedImage')

    for img in AnalyzedImage.objects.all():
        img.info, img.info_en = img.info_en, default_yaml
        img.save()


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0026_auto_20180828_1746'),
    ]

    operations = [
        migrations.RunPython(
            copy_analyses_texts,
            copy_back_analyses_texts,
        ),
    ]
