# Generated by Django 2.0.6 on 2018-08-29 16:59

from django.db import migrations, models
import tinymce.models
import yamlfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0027_auto_20180828_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='body_en',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='Conteúdo (EN)'),
        ),
        migrations.AlterField(
            model_name='action',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Título (EN)'),
        ),
        migrations.AlterField(
            model_name='analyzedimage',
            name='info_en',
            field=yamlfield.fields.YAMLField(blank=True, default='', verbose_name='Resultados da Análise (EN)'),
        ),
        migrations.AlterField(
            model_name='analyzedimage',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Posição'),
        ),
        migrations.AlterField(
            model_name='analyzedimage',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nome (EN)'),
        ),
        migrations.AlterField(
            model_name='questiontag',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Descrição (EN)'),
        ),
        migrations.AlterField(
            model_name='questiontag',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Pergunta'),
        ),
        migrations.AlterField(
            model_name='questiontag',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Pergunta (EN)'),
        ),
    ]
