# Generated by Django 2.0.6 on 2018-09-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0028_auto_20180829_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questiontag',
            options={'ordering': ['id'], 'verbose_name': 'Pergunta', 'verbose_name_plural': 'Perguntas'},
        ),
    ]
