# Generated by Django 2.0.6 on 2018-09-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0029_auto_20180902_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedimage',
            name='optimized_image',
            field=models.ImageField(blank=True, null=True, upload_to='carousel-optm/', verbose_name='Imagem otimizada'),
        ),
    ]
