# Generated by Django 2.0.8 on 2018-11-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0030_analyzedimage_optimized_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Posição'),
        ),
    ]
