# Generated by Django 2.0.6 on 2018-08-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mce_filebrowser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filebrowserfile',
            name='file_type',
            field=models.CharField(choices=[('img', 'Imagem'), ('doc', 'Document')], max_length=3),
        ),
    ]
